[package]
name = "nevo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
ruzstd = "0.6.0"
cpio = "0.4.0"
file-mode = "0.1.2"
